name: CI Pipeline for FullProject

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Debug repository structure
      - name: List repository structure
        run: |
          echo "Root level:"
          ls -R

      # Step 3: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Adjust according to your Node.js version

      # Step 4: Install dependencies in LiveWeb
      - name: Install dependencies
        run: |
          cd Frontend/vite-project/LiveWeb
          npm install

      # Step 5: Build the Vite app
      - name: Build Vite app
        run: |
          cd Frontend/vite-project/LiveWeb
          npm run build
