name: CI Pipeline for Vite React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: List repository files to debug
      - name: List repository files
        run: ls -R

      # Step 3: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 4: Navigate to the project directory and install dependencies
      - name: Install dependencies
        run: |
          cd Frontend/vite-project/LiveWeb
          npm install

      # Step 5: Build the Vite app
      - name: Build Vite app
        run: |
          cd Frontend/vite-project/LiveWeb
          npm run build
